// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WMS.Infrastructure.Persistence;

#nullable disable

namespace WMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WMS.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            AnnouncementId = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 6, 11, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6717),
                            IsActive = true,
                            Message = "Welcome to the new Workforce Management System!",
                            Title = "Welcome to WMS"
                        },
                        new
                        {
                            AnnouncementId = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 6, 1, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6720),
                            IsActive = false,
                            Message = "The legacy system will be shut down next week.",
                            Title = "Legacy Shutdown"
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<double?>("TotalHours")
                        .HasColumnType("float");

                    b.Property<string>("WorkMode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmpId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            AttendanceDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 12, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 12, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 3,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        },
                        new
                        {
                            AttendanceId = 2,
                            AttendanceDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 12, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 12, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 4,
                            TotalHours = 8.0,
                            WorkMode = "Remote"
                        },
                        new
                        {
                            AttendanceId = 3,
                            AttendanceDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 12, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 12, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 5,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        },
                        new
                        {
                            AttendanceId = 4,
                            AttendanceDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 11, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 3,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        },
                        new
                        {
                            AttendanceId = 5,
                            AttendanceDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 11, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 4,
                            TotalHours = 8.0,
                            WorkMode = "Remote"
                        },
                        new
                        {
                            AttendanceId = 6,
                            AttendanceDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 11, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 5,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        },
                        new
                        {
                            AttendanceId = 7,
                            AttendanceDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 10, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 3,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        },
                        new
                        {
                            AttendanceId = 8,
                            AttendanceDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 10, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 4,
                            TotalHours = 8.0,
                            WorkMode = "Remote"
                        },
                        new
                        {
                            AttendanceId = 9,
                            AttendanceDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 10, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 5,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        },
                        new
                        {
                            AttendanceId = 10,
                            AttendanceDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 9, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 9, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 3,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        },
                        new
                        {
                            AttendanceId = 11,
                            AttendanceDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 9, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 9, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 4,
                            TotalHours = 8.0,
                            WorkMode = "Remote"
                        },
                        new
                        {
                            AttendanceId = 12,
                            AttendanceDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 9, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 9, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 5,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        },
                        new
                        {
                            AttendanceId = 13,
                            AttendanceDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 8, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 8, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 3,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        },
                        new
                        {
                            AttendanceId = 14,
                            AttendanceDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 8, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 8, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 4,
                            TotalHours = 8.0,
                            WorkMode = "Remote"
                        },
                        new
                        {
                            AttendanceId = 15,
                            AttendanceDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckIn = new DateTime(2026, 6, 8, 9, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2026, 6, 8, 17, 0, 0, 0, DateTimeKind.Local),
                            EmpId = 5,
                            TotalHours = 8.0,
                            WorkMode = "Office"
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            AuditId = 1,
                            Action = "Added",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 6, 6, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6767),
                            EntityName = "Employee",
                            RecordId = 3
                        },
                        new
                        {
                            AuditId = 2,
                            Action = "Modified",
                            CreatedBy = 2,
                            CreatedOn = new DateTime(2026, 6, 9, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6770),
                            EntityName = "Leave",
                            RecordId = 2
                        },
                        new
                        {
                            AuditId = 3,
                            Action = "Added",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 6, 7, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6773),
                            EntityName = "EmployeeProjectAllocation",
                            RecordId = 1
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ClientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientLocation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("ClientPhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ClientAddress = "123 Tech Lane",
                            ClientLocation = "New York",
                            ClientName = "TechCorp",
                            ClientPhoneNumber = 9999999991L,
                            Status = true
                        },
                        new
                        {
                            ClientId = 2,
                            ClientAddress = "456 Finance Blvd",
                            ClientLocation = "London",
                            ClientName = "GlobalFinance",
                            ClientPhoneNumber = 9999999992L,
                            Status = true
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT",
                            Description = "Information Technology"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "HR",
                            Description = "Human Resources"
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Finance",
                            Description = "Finance Department"
                        },
                        new
                        {
                            DepartmentId = 4,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Operations",
                            Description = "Operations Department"
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOJ")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "admin@wms.com",
                            FirstName = "System",
                            Gender = "M",
                            LastName = "Admin",
                            PhoneNumber = "1111111111",
                            RoleId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeId = 2,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "manager@wms.com",
                            FirstName = "System",
                            Gender = "F",
                            LastName = "Manager",
                            PhoneNumber = "2222222222",
                            RoleId = 2,
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeId = 3,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "rahul@wms.com",
                            FirstName = "Rahul",
                            Gender = "M",
                            LastName = "Sharma",
                            PhoneNumber = "3333333333",
                            RoleId = 3,
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeId = 4,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = new DateTime(1992, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "priya@wms.com",
                            FirstName = "Priya",
                            Gender = "F",
                            LastName = "Singh",
                            PhoneNumber = "4444444444",
                            RoleId = 3,
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeId = 5,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOJ = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "amit@wms.com",
                            FirstName = "Amit",
                            Gender = "M",
                            LastName = "Kumar",
                            PhoneNumber = "5555555555",
                            RoleId = 3,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.EmployeeProjectAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AllocationId");

                    b.HasIndex("EmpId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProjectAllocations");

                    b.HasData(
                        new
                        {
                            AllocationId = 1,
                            AssignedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            EmpId = 3,
                            ProjectId = 1,
                            Status = true
                        },
                        new
                        {
                            AllocationId = 2,
                            AssignedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            EmpId = 4,
                            ProjectId = 2,
                            Status = false
                        },
                        new
                        {
                            AllocationId = 3,
                            AssignedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            EmpId = 5,
                            ProjectId = 3,
                            Status = true
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.Leave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmpId");

                    b.ToTable("Leaves");

                    b.HasData(
                        new
                        {
                            LeaveId = 1,
                            AppliedOn = new DateTime(2026, 6, 11, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6576),
                            EmpId = 3,
                            FromDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            LeaveType = "Sick",
                            Reason = "Fever",
                            Status = "Pending",
                            ToDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            LeaveId = 2,
                            AppliedOn = new DateTime(2026, 6, 11, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6582),
                            ApprovedBy = 2,
                            ApprovedOn = new DateTime(2026, 6, 11, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6583),
                            EmpId = 4,
                            FromDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            LeaveType = "Vacation",
                            Reason = "Trip",
                            Status = "Approved",
                            ToDate = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            LeaveId = 3,
                            AppliedOn = new DateTime(2026, 6, 11, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6588),
                            ApprovedBy = 2,
                            ApprovedOn = new DateTime(2026, 6, 11, 20, 0, 59, 407, DateTimeKind.Utc).AddTicks(6589),
                            EmpId = 5,
                            FromDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            LeaveType = "Casual",
                            Reason = "Family event",
                            Status = "Rejected",
                            ToDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectName = "WMS Project",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            ProjectId = 2,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectName = "HR Portal",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Inactive"
                        },
                        new
                        {
                            ProjectId = 3,
                            ClientId = 2,
                            EndDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectName = "Finance Dashboard",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "System Administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Department Manager",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Regular Employee",
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.UserLogin", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PasswordHash = "$2a$11$fBzVsc515Mpa25JqOKMX4uO6.cFT4Aqho9eRmtOzsaE6dIDCcQ9ay",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            PasswordHash = "$2a$11$jShHrfEX3hmjHHBDWYkOuu7sRhIbvLKZk1VYVVsq8sLPK4RdEYEaW",
                            RoleId = 2,
                            Username = "manager"
                        },
                        new
                        {
                            UserId = 3,
                            PasswordHash = "$2a$11$0YWVoOiAnhC5/1hSLKH1J.Jknbt6oqNKUDiagArnDHq4sQahPfXVK",
                            RoleId = 3,
                            Username = "rahul"
                        },
                        new
                        {
                            UserId = 4,
                            PasswordHash = "$2a$11$0YWVoOiAnhC5/1hSLKH1J.Jknbt6oqNKUDiagArnDHq4sQahPfXVK",
                            RoleId = 3,
                            Username = "priya"
                        },
                        new
                        {
                            UserId = 5,
                            PasswordHash = "$2a$11$0YWVoOiAnhC5/1hSLKH1J.Jknbt6oqNKUDiagArnDHq4sQahPfXVK",
                            RoleId = 3,
                            Username = "amit"
                        });
                });

            modelBuilder.Entity("WMS.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("WMS.Domain.Entities.UserLogin", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WMS.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("WMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WMS.Domain.Entities.Employee", b =>
                {
                    b.HasOne("WMS.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Domain.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WMS.Domain.Entities.EmployeeProjectAllocation", b =>
                {
                    b.HasOne("WMS.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeProjectAllocations")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS.Domain.Entities.Project", "Project")
                        .WithMany("EmployeeProjectAllocations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WMS.Domain.Entities.Leave", b =>
                {
                    b.HasOne("WMS.Domain.Entities.UserLogin", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WMS.Domain.Entities.Project", b =>
                {
                    b.HasOne("WMS.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WMS.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("WMS.Domain.Entities.Role", "Role")
                        .WithMany("UserLogins")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WMS.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WMS.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("EmployeeProjectAllocations");

                    b.Navigation("Leaves");
                });

            modelBuilder.Entity("WMS.Domain.Entities.Project", b =>
                {
                    b.Navigation("EmployeeProjectAllocations");
                });

            modelBuilder.Entity("WMS.Domain.Entities.Role", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("UserLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
